### ISSUE TITLE
Create HTML Email Template for "Application Received"

### ISSUE THREAD

**Issue by senuravihanjayadeva** [ms-club-sliit/msclub-backend#81]
You have to create a html email template for application received status.

Structure should be same as below. Please refer the contact us html template.

-----------------------------------------------------------------------------
Subject: Application Received - MS Club of SLIIT

Hi [Applicant Name],

Thank you for taking the time to apply for MS Club of SLIIT. We appreciate your interest. We would like to inform you that we have received your application. We will keep you informed of the status of your application.

Thanks again for taking the time to apply for MS Club of SLIIT

**Comment by rusiruavb** [comment]
Added to the bucket
